version: '3'
services:

  iq-server:
    image: 'sonatype/my-iq-server:1.59.0'
    build: ./iq-server
    volumes:
      - '~/iq-data:/sonatype-work'
    ports:
      - '8070:8070'
      - '8071:8071'

  nginx-proxy:
    build: ./nginx
    image: 'cmyanko/sonatype_nginx-proxy:2.4'
    ports:
      - '443:443'
      - '5000:5000'
      - '8011:8011'
      - '18443:18443'
    command:
      - nginx
      - '-g'
      - daemon off;

  nexus:
    image: 'cmyanko/nexus3:3.15.1'
    build: ./nexus
    volumes:
      - '~/nexus-data:/nexus-data'
    ports:
      - '8081:8081'

  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - '~/.jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8080:8080'
      - '50000:50000'
